/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.mantenimientos;

import Views.DashboardInterface;
import java.util.Date;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import model.Categories;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Fabricio
 */
public class CategoriesPanel extends javax.swing.JPanel {

    private DashboardInterface dashboardInterface;
    DefaultTableModel modelo;
    ArrayList<Categories> array;
    
    /**
     * Creates new form CategoriesPanel
     */
    public CategoriesPanel(DashboardInterface dashboardInterface) {
        initComponents();
        
        this.dashboardInterface = dashboardInterface;
        array = new ArrayList<Categories>();
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Fech_actual");
        modelo.addColumn("Fech_crea");
        tbl.setModel(modelo);
    }

    public Categories buscar(String Nom)
    {
        Categories emp;
        for (int i=0; i<array.size(); ++i)
        {
            if(Nom.equals(array.get(i).getID()))
            {
             return array.get(i);   
            } 
                
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnModificar1 = new javax.swing.JButton();
        txtDatos1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFA = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFC = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        txtFltrar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Elephant", 0, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        btnModificar1.setBackground(new java.awt.Color(255, 0, 0));
        btnModificar1.setText("Modicar");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnModificar1)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 388, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Fecha de creación", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 388, 196));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 239, -1));

        jLabel4.setText("Año de creación");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 95, -1));

        jLabel1.setText("ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 56, 22));
        add(txtFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 141, -1));
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 143, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("Categorias");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 225, -1));

        jLabel6.setText("Ingresa el ID ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 130, 25));
        add(txtFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 141, -1));

        btnCrear.setBackground(new java.awt.Color(255, 0, 0));
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, -1));

        txtFltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFltrarActionPerformed(evt);
            }
        });
        add(txtFltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 239, 23));

        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 56, -1));
        add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 142, -1));

        jLabel3.setText("Estado");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 95, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.setFocusTraversalPolicyProvider(true);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 239, -1));

        btnReturn.setBackground(new java.awt.Color(255, 0, 0));
        btnReturn.setText("Regresar");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        int fil = tbl.getSelectedRow();
        int col = tbl.getSelectedColumn();
        modelo.setValueAt(txtDatos1.getText(), fil, col);
        String id = (String)tbl.getValueAt(fil, 0);
        String nom = (String)tbl.getValueAt(fil, 0);
        String fech_crea = (String)tbl.getValueAt(fil, 0);
        String estado = (String)tbl.getValueAt(fil, 0);
        float esta = Float.parseFloat(estado);
        JOptionPane.showMessageDialog(null,"Se modifico correctamente");
        Categories emp = new Categories(id, nom, fech_crea, esta);
        array.set(fil,emp);
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tbl.getSelectedRow();
        if(fila>=0)

        {
            array.remove(fila);
            modelo.removeRow(fila);

        }else{

            JOptionPane.showMessageDialog(null,"Seleccionar Fila");

        }
        }

        public  DefaultTableModel getAllCat() {
            Object[] fila;  // una fila o array de objetos
            DefaultTableModel dtm = null;
            String colum[] = {"Codigo","Nombre", "Fecha_actual","Fecha_crea"};
            try
            {
                dtm = new DefaultTableModel();
                for(int i=0; i<colum.length; ++i)
                {
                    // Guardando nombres de campos en el DefaultTableModel
                    dtm.addColumn(colum[i]);
                }

                // creando una fila o array de objects (1 object por cada DATO)
                fila = new Object[colum.length];
                // while para sacar los datos del ResulSet --> rs
                for(int f=0; f<array.size(); ++f)
                {
                    fila[0] = array.get(f).getID();
                    fila[1] = array.get(f).getNombre();
                    fila[2] = array.get(f).getFech_actual();
                    fila[3] = array.get(f).getFech_crea();
                    //todos los datos se guardan en el objeto datos
                    dtm.addRow(fila);
                }
            } catch (Exception e)
            {
                // cuerpo del catch
            }
            // retorna los datos de todos empleados
            return dtm;
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String ID,Nom,FA,FC;
        String [] info = new String[4];
        info[0]= ID = txtID.getText();
        info[1]= Nom = txtNom.getText();
        info[2]= FA = txtFA.getText();
        info[3]= FC = txtFC.getText();
        float Fech_crea = Float.parseFloat(txtFC.getText());
        modelo.addRow(info);

        Categories emp = new Categories(ID,Nom,FA,Fech_crea);
        array.add(emp);
        txtID.setText("");
        txtNom.setText("");
        txtFA.setText("");
        txtFC.setText("");
        txtID.requestFocus();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtFltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFltrarActionPerformed

    }//GEN-LAST:event_txtFltrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String Filtrar = txtFltrar.getText();
        Categories emp = buscar(Filtrar);
        if(emp!=null){
            txtID.setText(emp.getID());
            txtNom.setText(emp.getNombre());
            txtFA.setText(emp.getFech_actual());
            txtFC.setText(emp.getFech_crea()+"");

        }else
        {

            JOptionPane.showMessageDialog(null,"" + Filtrar + "No existe");

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        dashboardInterface.switchPanel("Mantenimientos");
    }//GEN-LAST:event_btnReturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtDatos1;
    private javax.swing.JTextField txtFA;
    private javax.swing.JTextField txtFC;
    private javax.swing.JTextField txtFltrar;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
