/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.mantenimientos;

import Views.DashboardInterface;
import java.awt.BorderLayout;

/**
 *
 * @author Carlos Fabricio
 */
public class MantenimientosPreview extends javax.swing.JPanel {

    private DashboardInterface dashboardInterface;
    
    /**
     * Creates new form MantenimientosPreview
     */
    public MantenimientosPreview(DashboardInterface dashboardInterface) {
        initComponents();
        this.dashboardInterface = dashboardInterface;
        //setLayout(new BorderLayout()); Esto hace que no se vea tu ventana
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProdManagement = new javax.swing.JButton();
        btnCatManagement = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));

        btnProdManagement.setText("Productos");
        btnProdManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdManagementActionPerformed(evt);
            }
        });

        btnCatManagement.setText("Categorias");
        btnCatManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatManagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnProdManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCatManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProdManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCatManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatManagementActionPerformed
        dashboardInterface.switchPanel("Categorias");    
    }//GEN-LAST:event_btnCatManagementActionPerformed

    private void btnProdManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdManagementActionPerformed
        dashboardInterface.switchPanel("Productos");    
    }//GEN-LAST:event_btnProdManagementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatManagement;
    private javax.swing.JButton btnProdManagement;
    // End of variables declaration//GEN-END:variables
}
